set -euo pipefail

IMAGES_DIR="images"
OUT_DIR="generated"
OUT_FILE="${OUT_DIR}/gallery-data.js"

mkdir -p "$OUT_DIR"

{
  echo "// AUTO-GENERATED by build.sh — NEUPRAVOVAŤ RUČNE"
  echo "// Spustiť: bash build.sh"
  echo "// Generované: $(date -u '+%Y-%m-%dT%H:%M:%SZ')"
  echo ""
} > "$OUT_FILE"

echo "Skenujem ${IMAGES_DIR}/ ..."

found=0

for dir in "${IMAGES_DIR}"/*/; do
  [ -d "$dir" ] || continue

  dirname=$(basename "$dir")
  varname=$(printf '%s' "$dirname" | tr '[:lower:]' '[:upper:]' | tr -- '-' '_' | tr ' ' '_')

  files=()
  while IFS= read -r -d '' f; do
    files+=("$f")
  done < <(find "$dir" -maxdepth 1 \( \
      -iname "*.jpg"  -o -iname "*.jpeg" \
      -o -iname "*.png" -o -iname "*.webp" \
      -o -iname "*.avif" \
    \) -type f -print0 | sort -z)

  printf 'var GALLERY_%s = [' "$varname" >> "$OUT_FILE"

  first=true
  for f in "${files[@]+"${files[@]}"}"; do
    path="${f#./}"       
    path="${path//\\/\/}"   
    if [ "$first" = true ]; then
      first=false
    else
      printf ',' >> "$OUT_FILE"
    fi
    printf '"%s"' "$path" >> "$OUT_FILE"
  done

  printf '];\n' >> "$OUT_FILE"

  count=${#files[@]}
  echo "  GALLERY_${varname}: ${count} obrázok/ov (${dir})"
  found=$((found + 1))
done

echo "" >> "$OUT_FILE"

if [ "$found" -eq 0 ]; then
  echo "  ⚠  Nenašli sa žiadne podpriečinky v ${IMAGES_DIR}/"
else
  echo ""
  echo "✓  Vygenerované: ${OUT_FILE}"
fi
